name: Publish to Github Packages

on:
  workflow_run:
    workflows: [ Prepare release NPM ]
    types: [ completed ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1


      - name: Set env
        run: echo "RELEASE_VERSION=${{ steps.extract-release-notes.outputs.release_notes }}" >> $GITHUB_ENV
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: run build
        run: |
          cd wrap-materials/

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
